# handlers file for nginx
  - name: validate nginx config
    command: nginx -t
    register: nginx_test
    changed_when: false
    failed_when: nginx_test.rc != 0

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    notify: validate nginx config
