---
# tasks file for mysql

  - name: Install MySQL and Python support
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - mysql-server
      - python3-mysqldb
    tags: ['packages']

  - name: Ensure MySQL listens on all interfaces
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      insertafter: '^\[mysqld\]'
    notify: restart mysql
    tags: ['configure']

  - name: Ensure MySQL is started and enabled
    service:
      name: mysql
      state: started
      enabled: yes
    tags: ['service']

  - name: Ensure MySQL is started (Docker fallback)
    command: service mysql start
    when: ansible_virtualization_type == "docker"
    tags: ['service']

  - name: Create demo database
    mysql_db:
      name: "{{ db_name }}"
      state: present
    tags: ['configure']

  - name: Create demo user with access from any host
    mysql_user:
      name: "{{ db_user_name }}"
      password: "{{ db_user_pass }}"
      priv: "{{ db_name }}.*:ALL"
      host: "{{ db_user_host }}"
      state: present
    tags: ['configure']
