---
  - hosts: loadbalancer
    gather_facts: false
    tasks:
      - name: Stop nginx
        service:
          name: nginx
          state: stopped

      - name: Wait for nginx port 80 to drain
        wait_for:
          port: 80
          state: drained

  - hosts: webserver
    gather_facts: false
    tasks:
      - name: Stop apache2
        service:
          name: apache2
          state: stopped

      - name: Wait for apache2 port 80 to stop
        wait_for:
          port: 80
          state: stopped

  - hosts: database
    gather_facts: false
    tasks:
      - name: Restart MySQL
        service:
          name: mysql
          state: restarted

      - name: Wait for MySQL port 3306 to be available
        wait_for:
          port: 3306
          state: started

  - hosts: webserver
    gather_facts: false
    tasks:
      - name: Start apache2
        service:
          name: apache2
          state: started

      - name: Wait for apache2 port 80 to be available
        wait_for:
          port: 80
          state: started

  - hosts: loadbalancer
    gather_facts: false
    tasks:
      - name: Start nginx
        service:
          name: nginx
          state: started

      - name: Wait for nginx port 80 to be available
        wait_for:
          port: 80
          state: started
